services:
  - type: web
    name: elritmo-de-shine
    env: static
    buildCommand: echo "No build needed for static site"
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000
      - path: /index.html
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /visualization.html
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
